### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by lakka820** [plummm/SyzScope#14]
Hi， I  have used the image-ready2go, but when running the example, there will always be a requests.exceptions.ConnectionError error. I have investigated DNS, firewall, and network issues, but the problem remains unresolved.
docker pull etenal/syzscope:ready2go
docker run -it -d --name syzscope -p 2222:22 --privileged etenal/syzscope:ready2go
docker attach syzscope
cd /root/SyzScope
git pull

root@a9155f7a0272:~/SyzScope# python3 syzscope -i f99edaeec58ad40380ed5813d89e205861be2896
[+] Building image
[+] Building gcc and clang
[+] Building llvm
[+] Build static analysis tool
[+] Download pwndbg
[+] Setup golang environment
[+] Setup syzkaller
[+] Clean unfinished jobs
rm: cannot remove 'linux-*/.git/index.lock': No such file or directory
Removing index.lock
rm: cannot remove 'linux-*/THIS_KERNEL_IS_BEING_USED': No such file or directory
All set
[*] hash: f99edaeec58ad40380ed5813d89e205861be2896
[*] url: https://syzkaller.appspot.com/upstream/fixed
[*] max: 9999
[*] key: ['']
[*] deduplicate: []
[*] alert: ['']
root : root kvm
KVM is ready to go
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7efd6f2f84e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='syzkaller.appspot.com', port=443): Max retries exceeded with url: /bug?id=f99edaeec58ad40380ed5813d89e205861be2896 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efd6f2f84e0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "syzscope/__main__.py", line 305, in <module>
    crawler.run_one_case(args.input)
  File "/root/SyzScope/syzscope/modules/syzbotCrawler.py", line 85, in run_one_case
    if self.retreive_case(hash) == -1:
  File "/root/SyzScope/syzscope/modules/syzbotCrawler.py", line 122, in retreive_case
    detail = self.request_detail(hash)
  File "/root/SyzScope/syzscope/modules/syzbotCrawler.py", line 215, in request_detail
    tables = self.__get_table(url)
  File "/root/SyzScope/syzscope/modules/syzbotCrawler.py", line 278, in __get_table
    req = requests.request(method='GET', url=url)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='syzkaller.appspot.com', port=443): Max retries exceeded with url: /bug?id=f99edaeec58ad40380ed5813d89e205861be2896 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efd6f2f84e0>: Failed to establish a new connection: [Errno 111] Connection refused',))
root@a9155f7a0272:~/SyzScope#

**Comment by plummm** [comment]
What is the return of running this command `curl https://syzkaller.appspot.com/bug\?id\=f99edaeec58ad40380ed5813d89e205861be2896`

**Comment by plummm** [comment]
Dont need to paste the whole content if it's too long

**Comment by lakka820** [comment]
The return is :curl: (7) Failed to connect to syzkaller.appspot.com port 443: Connection refused.
But when I run the command out of the docker, the return is correct.  
Image-ready2go did not report an error when downloading.
How to Test or solve it.
Thanks very much.

**Comment by plummm** [comment]
It might be something wrong related to your docker environment. Try to google the solution for the docker network issue. If it's still not working, try manually setup SyzScope on the host machine. The tutorial is on the README
