### ISSUE TITLE
[BUG] syzbotCrawler is unable to correctly parse the syzbot fixed pages and causes AttributeError

### ISSUE THREAD

**Issue by QGrain** [plummm/SyzScope#6]
Hi, I am using Syzscope from the ready2go docker and got the following Error:

```bash
root@ea0c0bd44dff:~/SyzScope# python3 syzscope -k="INFO:" -RP -KF --timeout-kernel-fuzzing 3 -SA --timeout-static-analysis 3600 -pm 8 --debug
[+] Building image
[+] Building gcc and clang
[+] Building llvm
[+] Build static analysis tool
[+] Download pwndbg
[+] Setup golang environment
[+] Setup syzkaller
[+] Clean unfinished jobs
rm: cannot remove 'linux-*/.git/index.lock': No such file or directory
Removing index.lock
rm: cannot remove 'linux-*/THIS_KERNEL_IS_BEING_USED': No such file or directory
All set
[*] hash: None
[*] url: https://syzkaller.appspot.com/upstream/fixed
[*] max: 9999
[*] key: ['INFO:']
[*] deduplicate: []
[*] alert: ['']
root : root kvm
KVM is ready to go
debug mode runs on single thread
INFO    | 2023-03-22 07:16:27,727 | syzscope.modules.syzbotCrawler | Get table from https://syzkaller.appspot.com/upstream/fixed
DEBUG   | 2023-03-22 07:16:42,409 | syzscope.modules.syzbotCrawler | [0] Find a suitable case:
INFO: rcu detected stall in ext4_file_write_iter (6)
ext4

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "syzscope/__main__.py", line 316, in <module>
    crawler.run()
  File "/root/SyzScope/syzscope/modules/syzbotCrawler.py", line 68, in run
    cases_hash, high_risk_impacts = self.gather_cases()
  File "/root/SyzScope/syzscope/modules/syzbotCrawler.py", line 195, in gather_cases
    href = title.next.attrs['href']
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 742, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'NavigableString' object has no attribute 'attrs'
```

- Test envrironment: `etenal/syzscope:ready2go` with `git pull`
- Test command: `python3 syzscope -k="WARNING" -k="INFO:" -RP -KF --timeout-kernel-fuzzing 3 -SA --timeout-static-analysis 3600 -pm 8 --debug`
    - (**Note that**, the simpler command: `python3 syzscope -k="INFO:"` has the same error as well)

I briefly analyze the error trace and the syzbot page printed by debug mode. I think maybe the code `href = title.next.attrs['href']` in `syzbotCrawler.py:195` no longer fits the current format of the syzbot pages. *Not sure about this*, I guess there may be some compatibility issues in other format parsers which are hard-encoded in the crawler.

**Comment by plummm** [comment]
Fixed in the latest commit.
